baseURL = "https://www.synergyws.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Book a Space"
url = "https://synergyworkspace.app.proximity.space/account/memberships/change"
weight = 3
[[menu.main]]
name = "Login"
url = "https://synergyworkspace.app.proximity.space/account/memberships/change"
weight = 4
